### ISSUE TITLE
Upgrade to node-green version that supports latest ES_VERSIONS

### ISSUE THREAD

**Issue by 0xdevalias** [g-plane/node-green-cli#3]
Now that the following have been resolved in `node-green`:

- https://github.com/g-plane/node-green/issues/2
  - https://github.com/g-plane/node-green/pull/3

It would be awesome if this CLI could be updated to use that fixed version.

I'm not sure that those changes have been released as an updated package yet though:

- https://github.com/g-plane/node-green/commits/master

![image](https://user-images.githubusercontent.com/753891/216483802-bb16be5a-d350-4eb3-9f3f-972b60f2a36d.png)

**Comment by g-plane** [comment]
I'll release later.

**Comment by g-plane** [comment]
Both "node-green" and "node-green-cli" are released with new versions.

**Comment by 0xdevalias** [comment]
@g-plane Awesome! Thankyou!
